iearn-finance/iearn-finance

src/components/investSimple/investSimple.jsx
src/stores/store.jsx

Added MAX APR to the asset accordians

---

src/components/investSimple/investSimple.jsx

Fix for accordion not minimizing on close.

---

src/components/investSimple/asset.jsx
src/components/investSimple/investSimple.jsx
src/components/unlock/hooks.jsx
src/components/unlock/unlock.jsx
src/stores/store.jsx

Added V1 Contract Hide toggle
Changed TrustWallet from Injected Connector to WalletConnect connector
Removed some debug logging
Add new contracts with { version: 2 } in the assets:[] struct in the store to exclude them from the hide toggle.

Added V1 Contract Hide toggle

---

src/components/apr/apr.jsx
src/components/investSimple/investSimple.jsx

Hide language selector.

---

src/components/investSimple/investSimple.jsx

Showing V1 contracts by default.

---

src/App.js
src/components/home/home.jsx

Fixed responsiveness on home screen

---

src/components/insure/insuredAsset.jsx

Color expected return + premium

Disable buy cover when expected returns < 0

---

src/components/insure/insure.jsx
src/stores/store.jsx

Added TX hash in snackbar on buy cover returned

Fix conversion of ETH price.

---

src/components/investSimple/investSimple.jsx
src/components/zap/conversionRatios.jsx
src/components/zap/want.jsx
src/components/zap/zap.jsx
src/stores/store.jsx

Sorting by balance on the earn screen.

---

package.json
src/components/investSimple/investSimple.jsx
src/theme/theme.jsx

Upgraded @material-ui/core and added @material-ui/labs

New toggle for contract versions.

---

src/components/pool/exchange/exchange.jsx

Input validation on Exchange

---

src/components/pool/deposit/deposit.jsx
src/stores/store.jsx

Deposit pool calculates off of default values.
TX Hash returning for Deposit and Withdraw pools. (correct event emitted)

Exchange pool

---

src/components/pool/deposit/deposit.jsx
src/stores/store.jsx

On Deposit, call approvals synchronously.
Validate that an amount other than sUSD is populated before deposit

Deposit pool

---

src/stores/store.jsx

Async Sync approval for deposits V2

---

src/components/pool/deposit/deposit.jsx
src/locales/en/translation.json

Added deposit breakdown for recommended tokens.

---

.gitignore
src/components/investSimple/investSimple.jsx

While connecting with Coinbase Wallet after the successful connection,
application throws: `TypeError: Cannot read property 'toFixed' of undefined`
I have added checks for the properties before calling `toFixed` and put `N/A` as default value.

Added checks investSimple.jsx

---

src/components/home/home.jsx

Fix typo on homepage

---

src/components/footer/footer.jsx

Not sure why the link to this tool was never added but I keep on using it to deposit USDC in yCrv

Added vaults.finance to footer links

---

package-lock.json
package.json
src/components/header/header.jsx

For user account address (top right of header page) show the account ENS name if available. Otherwise fallback to the truncated account address like we do today (0xadEa...fab9).

Resolves account address ENS name when available

---

src/components/footer/footer.jsx

Fix Discord link with one that's nice and works: http://discord.yearn.finance

Fix Discord link with one that's nice and works

---

src/i18n.js
src/locales/pt/translation.json
src/stores/store.jsx

Rebased and checked version of https://github.com/iearn-finance/iearn-finance/pull/70.
Ready for merge.

Add European Portuguese translation

---

src/components/apr/apr.jsx
src/components/dashboard/dashboard.jsx
src/components/vault/vault.jsx

Remove 3 day options from the Stats, Dashboard and Vault views

---

src/components/footer/footer.jsx

Closes #123 
Agree with the proposed change, can ping vany365 to update discord links also

Remove learn yearn link

---

src/components/footer/footer.jsx

Closes #124 
Renamed **Socials** to **Resources** and added to the bottom under Github

Add bug bounty link

---

src/components/vault/vault.jsx

Closes #125 
It would be cleaner to also remove LINK from the Redux store (`store.jsx`) but that would remove the Stats so using a filter for now.

Add prominent UI for deposit disabled vaults

---

src/components/zap/want.jsx

Removed default asset option so onChange event is triggered

Fix Zap button onChange event

---

.github/workflows/lint.yaml
commitlint.config.js

Close #133 
Enforces: https://github.com/conventional-changelog/commitlint/blob/master/docs/reference-rules.md

ci: add conventional linting

---

src/App.js

fix: add event listener for ethereum#initialized

---

src/components/apr/apr.jsx

feat: add simple aggregated stats

---

src/components/vault/asset.jsx

fix: incosistent apy display

---

src/stores/store.jsx

The YFI strat contract does not implement getName(), so hardcode the name of the strat in the UI for the time being. This matches the behavior of the USDC vault, which also does not implement getName().

Fetch strategy name from yearn api since not all strategy contracts implement getName()

---

.github/workflows/developDeploy.yml
.github/workflows/productionDeploy.yml

- Develop branch builds and deploys https://dev.yearn.finance
- Master branch builds and deploys https://yearn.finance

ci: update branches and CloudFront distribution ID in CI deployment scripts (#148)

---

src/components/apr/apr.jsx
src/components/home/home.jsx
src/components/vault/vault.jsx
src/stores/store.jsx

Fixes minor build issues that causes the CI pipeline to fail on 'npm run-script build'

fix: minor fixes so build passes on CI

---

src/components/vault/asset.jsx

feat: add dai slippage warning

---

src/components/vault/asset.jsx

@milkyklim Take 2 - can you do a `merge --squash` for a cleaner the commit log?

 feat: add dai slippage warning

---

src/components/vault/asset.jsx

@milkyklim Take 3 - reverted back to `href` but added the `rel="noopener noreferrer"`. Replicated issue in local environment, so hopefully this is good.

fix: add dai slippage warning

---

src/components/apr/apr.jsx

@x48-crypto just small amendments following on from WrongNebula's feedback on #143

feat: enhance aggregate stats

---

src/components/lending/borrowAsset.jsx
src/components/lending/lending.jsx
src/components/lending/supplyAsset.jsx
src/stores/store.jsx

Added liquidity
Used BigNumber to calculate balances
Fixed Borrow limit calculations
Removed onInvest keydown on borrow and supply assets.

fix: cream

---

src/components/cover/newCover.jsx
src/stores/store.jsx

also fix some minor texts/var naming

fix: null balancer pool address

---

src/components/cover/existingCover.jsx
src/components/cover/newCover.jsx
src/stores/store.jsx

fix row display and pagination
add cover token balance and $ value

fix: cover ui

---

src/components/cover/newCover.jsx
src/stores/store.jsx

Instead of making users input amount of DAI to spend, they now input number of tokens they want

fix: user inputs number of wanted tokens

---

.github/workflows/developDeploy.yml
package-lock.json
src/components/header/header.jsx
src/stores/store.jsx

USDC / USDT weren't showing up with values on supplied assets.
Fixed,

fix: cream supplied amounts with decimals less than 18

---

src/components/lending/borrowAsset.jsx
src/components/lending/supplyAsset.jsx

fix(lending): ensure supplyAsset button text appears
